name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: cd vpc-terraform-github-actions
        id: init
        run: terraform init
        working-directory: ./vpc-terraform-github-actions
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./vpc-terraform-github-actions
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./vpc-terraform-github-actions
      - name: Terraform Apply
        id: apply
        run: terraform destroy --auto-approve
        working-directory: ./vpc-terraform-github-actions
